pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                bat 'mvn -f code/arith/pom.xml clean compile'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn -f code/arith/pom.xml test'
            }
        }
        stage('Package') {
            steps {
                bat 'mvn -f code/arith/pom.xml package'
            }
        }
    }
}