server.port: 7002

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db

---

spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: recommendation_db

server:
  port: 8080