
server.port: 7001

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

---

spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: product_db

server:
  port: 8080



