debug: true

server:
  port: 8181

spring:
  cloud:
    gateway:
      routes:
      - id: route1
        uri: http://localhost:8081
        predicates:
        - Path=/foo
        # - Header=foo-header 
      - id: route2
        uri: http://localhost:8082
        predicates:
        - Path=/bar
     
         
